name: replace docx field ci
on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go mod tidy && go build -o bin/docx-replacer cmd/main.go

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go mod tidy && go build -o bin/docx-replacer cmd/main.go